version: '3'
services:
    db:
        image: postgres:9.5.18
        environment:
            POSTGRES_HOST_AUTH_METHOD: 'trust'
    web:
        build: .
        command: python3 manage.py runserver '0.0.0.0:8001'
        volumes:
            - .:/code
        ports:
            - "8001:8001"
    
        environment:
            - POSTGRES_USER= postgres
            - POSTGRES_PASSWORD= postgres
            - POSTGRES_DB= db

        depends_on:
            - db

