# Generated by Django 2.0 on 2020-05-31 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hogehoge', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='SayHoge',
        ),
    ]
